### ISSUE TITLE
Too difficult

### ISSUE THREAD

**Issue by chellothere** [DargonXuan/AutoRiddleMaster#1]
我浪费了三个小时来制作这个剧本，但一切都是徒劳的，我现在想开枪自杀，谢谢。 会为 redmama 积累资金

I wasted three hours to make this script work but it all was in vain, I wanna shot myself now, thank you. Will accumulate my money for redmama instead.

**Comment by DargonXuan** [comment]
I have spent three months on building this, and it has been running steadily for six months so far. If you encounter difficulties, please bring it up.

**Comment by DargonXuan** [comment]
And now you don't need to use google docker, just run python api.py

**Comment by chellothere** [comment]
I am very far from coding, can you please explain to the stupid what to install first and where to click next

**Comment by DargonXuan** [comment]
https://stackoverflow.com/questions/61796196/heroku-tensorflow-2-2-1-too-large-for-deployment

> Turns out the Tensorflow 2.0 module is very large (more than 500MB, the limit for Heroku) because of its GPU support. Since Heroku doesn't support GPU, it doesn't make sense to install the module with GPU support.
> 
> Solution:
> Simply replace tensorflow with tensorflow-cpu in your requirements.
> 
> This worked for me, hope it works for you too!

**Comment by DargonXuan** [comment]
A more detailed tutorial has been released, you can also install `user.js` directly, and then test it in test.autopony.ltd. 
If there are still problems, issue it.

**Comment by chellothere** [comment]
> A more detailed tutorial has been released, you can also install `user.js` directly, and then test it in test.autopony.ltd. If there are still problems, issue it.

Thank you, will try to setup now
