### ISSUE TITLE
How to set server address?

### ISSUE THREAD

**Issue by ohtanimvp** [DargonXuan/AutoRiddleMaster#6]
Hi, bro.
I'm a noob in programming.
Thank you for your detailed and clear explanation.
But the only one parameter: server address/API_SERVER, I don't know how to replace it.
Can you show me a example? 

I saw the line: host="0.0.0.0", port=9000; which means I need to set  server address/API_SERVER to 0.0.0.0:9000?
I tried but it didn't work.

Cheers,

**Comment by DargonXuan** [comment]
0.0.0.0 means any IP address you can connect to your computer.
If you deploy it on your own computer, you can use 127.0.0.1 or localhost instead.
`const API_SERVER = 'http://127.0.0.1';`
If you deploy on a server, it will be the public IP address of your server.

**Comment by ohtanimvp** [comment]
Thanks for reply, it works.

**Comment by DargonXuan** [comment]
> Thanks for reply, it works.

No thanks. I hope you can let more people use it.
